services:
  app:
    image: ghcr.io/gygmor/erd:latest
    container_name: tool_app
    networks:
      - web
    env_file:
      - .env
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: always

networks:
  web:
    external: true
